import { db } from "./db";
import { products } from "@shared/schema";

const seedProducts = [
  {slug:"anua-heartleaf-77-soothing-toner",name:"Heartleaf 77% Soothing Toner",brand:"Anua",category:"Toners",description:"A gentle, hydrating toner formulated with 77% heartleaf extract to calm and soothe sensitive, irritated skin. Lightweight and fast-absorbing, it preps the skin for the next steps in your routine.",image:"/images/products/anua-toner.png",priceHKD:162,originalPriceHKD:228,volume:"250ml",tags:["Best Seller","Soothing","Acne Care"],featured:true,inStock:true,costKrw:18000,marginPercent:30,shippingHkd:20,status:"live" as const},
  {slug:"roundlab-1025-dokdo-toner",name:"1025 Dokdo Toner",brand:"Round Lab",category:"Toners",description:"Infused with deep sea water from Ulleungdo Island, this toner gently exfoliates while providing essential moisture. Ideal for combination and oily skin types looking for lightweight hydration.",image:"/images/products/roundlab-toner.png",priceHKD:136,originalPriceHKD:189,volume:"200ml",tags:["Exfoliating","Hydrating","Mineral Rich"],featured:true,inStock:true,costKrw:15000,marginPercent:30,shippingHkd:18,status:"live" as const},
  {slug:"cosrx-advanced-snail-96-mucin-essence",name:"Advanced Snail 96 Mucin Power Essence",brand:"COSRX",category:"Essences",description:"A best-selling essence enriched with 96% snail secretion filtrate to help repair damaged skin, fade scars, and deliver deep hydration for a healthy, radiant complexion.",image:"/images/products/cosrx-snail.png",priceHKD:122,originalPriceHKD:158,volume:"100ml",tags:["Repair","Glow","Hydration"],featured:true,inStock:true,costKrw:15000,marginPercent:18,shippingHkd:15,status:"live" as const},
  {slug:"missha-time-revolution-first-treatment-essence",name:"Time Revolution The First Treatment Essence 5X",brand:"Missha",category:"Essences",description:"A luxurious first-step essence fermented with 97% desert cica yeast to deliver intense nourishment, visibly brightened skin, and an even, youthful complexion.",image:"/images/products/missha-essence.png",priceHKD:178,originalPriceHKD:248,volume:"150ml",tags:["Anti-Aging","Brightening","Fermented"],featured:true,inStock:true,costKrw:20000,marginPercent:32,shippingHkd:18,status:"live" as const},
  {slug:"beauty-of-joseon-relief-sun",name:"Relief Sun: Rice + Probiotics SPF50+ PA++++",brand:"Beauty of Joseon",category:"Sunscreens",description:"A lightweight, chemical sunscreen with SPF50+ PA++++ that combines 30% rice extract and probiotics for a soothing, moisturising finish with no white cast.",image:"/images/products/boj-sunscreen.png",priceHKD:136,originalPriceHKD:175,volume:"50ml",tags:["SPF50+","No White Cast","Soothing"],featured:false,inStock:true,costKrw:16000,marginPercent:25,shippingHkd:15,status:"live" as const},
  {slug:"skin1004-madagascar-centella-sun-serum",name:"Madagascar Centella Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++",brand:"Skin1004",category:"Sunscreens",description:"A serum-textured sunscreen featuring centella asiatica from Madagascar and hyaluronic acid. Delivers broad-spectrum SPF50+ PA++++ protection with a dewy, hydrated finish.",image:"/images/products/skin1004-sun.png",priceHKD:160,originalPriceHKD:198,volume:"50ml",tags:["SPF50+","Hydrating","Dewy Finish"],featured:false,inStock:true,costKrw:20000,marginPercent:20,shippingHkd:15,status:"live" as const},
  {slug:"natural-core-eco-organic-dog-food",name:"ECO Organic Dry Dog Food",brand:"Natural Core",category:"Pet Food",description:"Korea's top-rated organic dog food made with free-range chicken and brown rice. USDA and EU organic certified, developed with Korean veterinary nutritionists.",image:"/images/products/naturalcore-dogfood.png",priceHKD:323,originalPriceHKD:420,volume:"2kg",tags:["Best Seller","Organic","Vet Approved"],featured:true,inStock:true,costKrw:38000,marginPercent:25,shippingHkd:35,status:"live" as const},
  {slug:"iskhan-grain-free-cat-food",name:"Grain-Free Indoor Cat Food",brand:"Iskhan",category:"Pet Food",description:"Premium Korean grain-free formula with real chicken as the first ingredient. Designed for indoor cats with added hairball control and urinary tract support.",image:"/images/products/iskhan-catfood.png",priceHKD:278,originalPriceHKD:380,volume:"2.5kg",tags:["Top Rated","Indoor Cat","Hairball Control"],featured:true,inStock:true,costKrw:32000,marginPercent:25,shippingHkd:35,status:"live" as const},
  {slug:"bowwow-freeze-dried-dog-treats",name:"Freeze-Dried Salmon Dog Treats",brand:"Bow Wow",category:"Pet Treats",description:"Single-ingredient freeze-dried wild salmon treats made in Korea. Over 15,000 five-star reviews on Coupang. Rich in omega-3 for healthy skin and coat.",image:"/images/products/bowwow-treats.png",priceHKD:93,originalPriceHKD:115,volume:"150g",tags:["Best Seller","Single Ingredient","Omega Rich"],featured:true,inStock:true,costKrw:9500,marginPercent:30,shippingHkd:18,status:"live" as const},
  {slug:"meowday-freeze-dried-cat-treats",name:"Freeze-Dried Chicken Breast Cat Treats",brand:"Meowday",category:"Pet Treats",description:"Korea's favourite cat treat with over 20,000 reviews. 100% Korean chicken breast, freeze-dried to preserve nutrients. No additives, no grain, pure protein.",image:"/images/products/meowday-treats.png",priceHKD:67,originalPriceHKD:85,volume:"100g",tags:["Top Rated","Single Ingredient","High Protein"],featured:true,inStock:true,costKrw:7000,marginPercent:30,shippingHkd:12,status:"live" as const},
  {slug:"forcans-aloe-pet-shampoo",name:"Aloe & Oatmeal Hypoallergenic Pet Shampoo",brand:"Forcans",category:"Pet Grooming",description:"Korea's best-selling pet shampoo with 12,000+ reviews. pH-balanced formula with Jeju aloe vera and colloidal oatmeal for sensitive dogs and cats.",image:"/images/products/forcans-shampoo.png",priceHKD:103,originalPriceHKD:138,volume:"500ml",tags:["Best Seller","Hypoallergenic","Jeju Aloe"],featured:true,inStock:true,costKrw:11000,marginPercent:28,shippingHkd:18,status:"live" as const},
  {slug:"arrr-macaron-cat-brush",name:"Macaron Self-Cleaning Cat Brush",brand:"ARRR",category:"Pet Grooming",description:"Award-winning Korean-designed grooming brush with one-click self-cleaning. Gentle rounded pins remove loose fur without irritating sensitive cat skin.",image:"/images/products/arrr-catbrush.png",priceHKD:125,originalPriceHKD:165,volume:"One Size",tags:["Award Winner","Self Cleaning","Gentle"],featured:false,inStock:true,costKrw:14000,marginPercent:30,shippingHkd:15,status:"live" as const},
  {slug:"petoria-omega-supplement",name:"Omega 3-6-9 Skin & Coat Supplement",brand:"Petoria",category:"Pet Health",description:"Korean veterinary-formulated supplement with anchovy oil and evening primrose. Over 9,000 reviews for improving dry skin, dull coats, and joint health in dogs and cats.",image:"/images/products/petoria-supplement.png",priceHKD:177,originalPriceHKD:238,volume:"120 Softgels",tags:["Vet Formulated","Skin & Coat","Joint Support"],featured:true,inStock:true,costKrw:20000,marginPercent:28,shippingHkd:22,status:"live" as const},
  {slug:"catcure-dental-care-gel",name:"Enzymatic Dental Care Gel for Cats",brand:"CatCure",category:"Pet Health",description:"Developed by Korean veterinary dentists. Enzymatic gel that breaks down plaque and tartar. Fish flavour cats love — no brushing required. 8,500+ reviews.",image:"/images/products/catcure-dental.png",priceHKD:100,originalPriceHKD:138,volume:"50ml",tags:["Dental Care","No Brushing","Vet Developed"],featured:false,inStock:true,costKrw:11000,marginPercent:28,shippingHkd:15,status:"live" as const},
  {slug:"petsbe-interactive-cat-toy",name:"Smart Interactive Cat Feather Toy",brand:"PetsBe",category:"Pet Accessories",description:"Korea's #1 automatic cat toy with irregular movement patterns that mimic real prey. USB rechargeable, whisper-quiet motor. 14,000+ glowing reviews.",image:"/images/products/petsbe-cattoy.png",priceHKD:139,originalPriceHKD:188,volume:"One Size",tags:["Best Seller","Auto Play","USB Charging"],featured:true,inStock:true,costKrw:16000,marginPercent:25,shippingHkd:18,status:"live" as const},
  {slug:"arrr-dog-harness-vest",name:"Air Mesh Comfort Dog Harness",brand:"ARRR",category:"Pet Accessories",description:"Award-winning Korean-designed breathable mesh harness. Evenly distributes pressure to prevent choking. Reflective strips for night safety. 11,000+ reviews.",image:"/images/products/arrr-harness.png",priceHKD:166,originalPriceHKD:228,volume:"Medium",tags:["Award Winner","Breathable","Reflective"],featured:true,inStock:true,costKrw:19000,marginPercent:25,shippingHkd:22,status:"live" as const},
];

export async function seedIfEmpty() {
  const existing = await db.select().from(products);
  if (existing.length > 0) {
    console.log(`Database has ${existing.length} products. Skipping seed.`);
    return;
  }

  console.log("Seeding products...");
  for (const product of seedProducts) {
    await db.insert(products).values(product);
    console.log(`  Added: ${product.brand} - ${product.name}`);
  }
  console.log(`Seeding complete! Added ${seedProducts.length} products.`);
}

